### ISSUE TITLE
Lost recordings

### ISSUE THREAD

**Issue by squidrpi** [gonzalo-hvega/pvr.sql#2] opened 2020-10-04 16:25 UTC
Set a timer to record, it then started and I checked it whilst it was recording. Recording ended on its own and then it got automatically deleted! No log in pvr.sql/log but kodi.log Error log is here:

https://pastebin.com/DnsicgcE

**Comment by gonzalo-hvega** [comment] 2020-10-05 19:44
What OS are you using?

It appears that when the plugin tried to get the file size it got back a zero (empty file), which is clearly wrong as the ffmpeg timestamp shows a 3 hour long recording, can you retry one more time and on the next log include the full filename? Maybe there was a special character for your OS.

**Comment by squidrpi** [comment] 2020-10-05 21:05
Rapid 3b libreelec 
Tried a different recording, 30 mins and it was fine. I didn’t attempt to watch this recording as it was being recorded but I did on this one that failed.
There were no special characters.

**Comment by gonzalo-hvega** [comment] 2020-10-06 02:21
Hmmm strange I will try to add more warnings and error notes to let me know what's going on, maybe it couldn't read the file because it was still locked. Closing for now, if it pops up again will send you a version with debug code.

**Comment by gonzalo-hvega** [comment] 2020-10-06 02:22
Closed until issue is reproduced.

**Closed as completed** 2020-10-06 02:22 UTC
